<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head><script type="text/javascript" src="../page_head.js"></script>

<h3><a href="../index.htm">掌機</a> - Pandora (Rebirth) - SuperZaxxon - <b>解決Config/hal: couldn't initialise context: unknown error null問題</b></h3>
<hr size="1"><br>
<p>
卡在登入畫面，鍵盤以及觸控都失效<br>
<img src="pandora_rebirth_superzaxxon_fix_hal/1.jpg" class="maxSize"><br><br>

幸好司徒有開啟SSH登入功能，查看了下<b>/var/log/Xorg.0.log</b>
</p>
<pre>
(II) Initializing built-in extension Generic Event Extension
(II) Initializing built-in extension SHAPE
(II) Initializing built-in extension MIT-SHM
(II) Initializing built-in extension XInputExtension
(II) Initializing built-in extension XTEST
(II) Initializing built-in extension BIG-REQUESTS
(II) Initializing built-in extension SYNC
(II) Initializing built-in extension XKEYBOARD
(II) Initializing built-in extension XC-MISC
(II) Initializing built-in extension XFIXES
(II) Initializing built-in extension RENDER
(II) Initializing built-in extension RANDR
(II) Initializing built-in extension COMPOSITE
(II) Initializing built-in extension DAMAGE
(EE) config/hal: couldn't initialise context: unknown error (null)
</pre><br>

<p>
發現Nub無法初始化
</p>
<pre>
$ /usr/pandora/scripts/op_nubmode.py 
    Traceback (most recent call last):
        File "/usr/pandora/scripts/op_nubmode.py", line 6, in <module>
            import gtk
        File "/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 30, in <module>
            import gobject as _gobject
        File "/usr/lib/python2.7/site-packages/gtk-2.0/gobject/__init__.py", line 26, in <module>
            from glib import spawn_async, idle_add, timeout_add, timeout_add_seconds, \
        File "/usr/lib/python2.7/site-packages/gtk-2.0/glib/__init__.py", line 22, in <module>
            from glib._glib import *
    ImportError: /usr/lib/libpyglib-2.0-python.so.0: undefined symbol: g_return_if_fail_warning
</pre><br>

<p>
司徒這才發現升級Python3後，添加<b>/etc/ld.so.conf</b>時，竟然忘記加入<b>/usr/lib</b>路徑，重新加入後並執行<b>ldconfig</b>即可
</p>
<pre>
/usr/local/lib
</pre>

<br><script type="text/javascript" src="../tail.js"></script>
